Add To Do List with all functionalities
dicodiaz/to-do-list-code-review pull request #1
Opened 2021-09-27 21:11 UTC by dicodiaz

All functionalities are:

* Adding a new item.
* Removing a selected item.
* Marking a selected item as complete.
* Removing all items marked as complete at once.
* Reordering a selected item with drag-and-drop.
* Task.js includes the Task class with all its methods.
* images.js includes functions to append images.
* index.js includes windows.onload function.

2021-09-28 14:46 UTC, KatIsCoding requested changes
## Hey! Your project is looking good! I really like the way you styled it and how you decided to use some OOP for some functionalities, however, I think there are some things I think should be changed, hopefully, you will be able to implement these changes and make your project look even better!

2021-09-28 14:46 UTC, KatIsCoding commented on src/Task.js
> +import Trash from './trash.png';
[OPTIONAL] I see you decided to use your own images for the different Icons and this is great under normal conditions where you wanted to import your own artwork, however, the icons used can be found in some online icons providers, for example, Google Icons and Fontawesome which you should consider using more the next time you have to import an image, this can save you a few steps while developing and, at the same time demonstrate you know how to use such APIs!

2021-09-28 14:46 UTC, KatIsCoding commented on src/Task.js
> +  }
- [x] I really like your OOP approach, however, it is kinda hard to follow up, especially because the `tasks` variable which is supposed to save all the different tasks is part of the `Task` class, this might be a small issue but it does great damage when trying to read and understand the code, maybe you should separate the methods regarding the `tasks` array from the actual `Task` class.
In a summarized conclusion, the `tasks` variable or the "Database" should be containing only the `Task` objects which are the ones that describe every task you will be storing, however, it doesn't make that much sense to save all the methods of `Task` class in every object, because anyways those methods only directly affect the whole `tasks` or database itself

2021-09-28 14:46 UTC, KatIsCoding commented on src/Task.js
> +  }
This refers to all your non-static methods (`populate`, `remove` and `add`)

2021-09-28 14:46 UTC, KatIsCoding commented on src/images.js
> +export { appendImg, appendCrossFadingImgs };
- [ ] Great job on creating these methods for image adding, however, you have to remember this process can be simplified by using other methods such as using Icons providers

2021-09-30 10:39 UTC, dicodiaz commented on src/Task.js
> +  }
Thanks for your review! I applied this.

2021-10-02 08:10 UTC, KatIsCoding approved these changes
## Good job applying the changes!! Now it will be way easier to maintain the code base of your project, congrats!! Now you can merge!

2021-10-05 16:25 UTC, merged